### ISSUE TITLE
Removed stacked areas chart

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#12]
https://github.com/Natixar/natixar-frontend/blame/ef02efb304be15fcc3db79dec95d395414c956e3/src/pages/natixar/ClimateChangePage.tsx#L95

The above commit commented out the second chart on the Climate Change Page (main dashboard).

Steps to reproduce: 
1 - Open dashboard. Consider changed navigation and click on "See total emissions"
2 - Only see the bar chart there, with comparison capability

Expected behavior:
The real-time streaming stacked area chart must be on the first page of the dashboard.

**Comment by astowny** [comment]
Corrected in 4ddbfb5f9f4fb5cc816dcb317116060e058c56ea

**Comment by lepeuvedic-natixar** [comment]
Not fixed.
I did not write that it was a bad thing to have the bar chart on a second page. We even had a prototype where the type of chart was dynamically selectable.
The nature of the bug was the removal of an existing chart, the stacked area chart with curves, which existed (and still exists) in the main branch.

**Comment by lepeuvedic-natixar** [comment]
The row of buttons to select the timescale is missing. Copy it over from the other chart (bar chart), although they are completely independent states so please be careful not to overwrite the state of the other chart.
